version: '2'
services:
    atlas-app:
        image: atlas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://atlas-mysql:3306/atlas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=atlas-elasticsearch:9300
        ports:
            - 8080:8080
    atlas-mysql:
        extends:
            file: mysql.yml
            service: atlas-mysql
    atlas-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: atlas-elasticsearch
